# Generated by Django 2.2.7 on 2019-11-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='health_tell',
            new_name='healthcenter_number',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='occupants_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
