# Generated by Django 2.2.7 on 2019-12-01 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghood', '0002_auto_20191130_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='hood_logo',
            new_name='neighbourhood_logo',
        ),
    ]
