# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-20 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to='landingpage/'),
        ),
    ]
